add iframe-resizer
gtap-dev/nighthawk pull request #2
Opened 2017-02-17 13:58 UTC by risker

2017-02-17 19:25 UTC, ArdoA requested changes
Ma vb tegin midagi valesti.. aga nende muudatusega mul ei õnnestu enam üldse scrollida iframe ala...

Konsoolis on warning (mitte error): [iFrameSizer][Host page: iFrameResizer17] No response from iFrame. Check iFrameResizer.contentWindow.js has been loaded in iFrame

2017-02-17 19:28 UTC, risker commented
baasrepos pead ka õiges harus olema

On Fri, 17 Feb 2017, 21:25 Ardo Aednik, <notifications@github.com> wrote:

> *@ArdoA* requested changes on this pull request.
>
> Ma vb tegin midagi valesti.. aga nende muudatusega mul ei õnnestu enam
> üldse scrollida iframe ala...
>
> Konsoolis on warning (mitte error): [iFrameSizer][Host page:
> iFrameResizer17] No response from iFrame. Check
> iFrameResizer.contentWindow.js has been loaded in iFrame
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gtap-dev/nighthawk/pull/2#pullrequestreview-22572971>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABze-1NKGpM0dE-CIn4FcKWHnbXXZWgPks5rdfQpgaJpZM4MES-G>
> .
>

2017-02-17 19:33 UTC, ArdoA commented
Ok, nii on. Ei pannud teist pull requesti tähelegi kohe.
Kas kuidagi on võimalik disableda/ülekirjutada ka seda komponendi configi vahendusel?

2017-02-20 14:57 UTC, ArdoA approved these changes

2017-02-20 15:04 UTC, merged